spring:
  profiles:
   active:
   - dev
---
spring:
  profiles: dev  #开发环境
  application:
   name: microservicecloud-config-xujian-dev
---
spring:
  profiles: test  #测试环境
  application:
   name: microservicecloud-config-xujian-test
